"""init wallet history

Revision ID: 433d64f1602e
Revises: 
Create Date: 2026-01-30 23:16:06.005878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433d64f1602e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('walletId', sa.Integer(), nullable=False),
    sa.Column('transactionType', sa.Enum('ADD', 'REMOVE', 'UPDATE', name='transaction_type_enum'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('previousAmount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['walletId'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transaction')
    # ### end Alembic commands ###
