"""wallet linked to a strategy

Revision ID: a106dc832f8a
Revises: 433d64f1602e
Create Date: 2026-02-05 14:37:01.090368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a106dc832f8a'
down_revision: Union[str, Sequence[str], None] = '433d64f1602e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('strategy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'strategy')
    # ### end Alembic commands ###
